name: Deploy Agent

on:
  push:
    branches: ["main"]

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ROLE: ${{ secrets.AWS_ROLE }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy-agent:
    runs-on: ubuntu-24.04-arm

    defaults:
      run:
        working-directory: agent

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install CDK
        run: |
          npm install -g aws-cdk

      - name: Deploy ECR
        working-directory: aws/ac-infra
        run: |
          npm i
          cdk deploy -O cdk-ecr-outputs.json --require-approval never

      - name: Parse ECR CDK outputs
        id: cdk_ecr_outputs
        working-directory: aws/ac-infra
        run: |
          REPO_NAME=$(jq -r '.RustAgentAgentcoreECRStack.ECRRepositoryName' cdk-ecr-outputs.json)
          REPO_URI=$(jq -r '.RustAgentAgentcoreECRStack.ECRRepositoryURI' cdk-ecr-outputs.json)
          COGNITO_DISCOVERY_URL=$(jq -r '.RustAgentAgentcoreECRStack.CognitoDiscoveryUrl' cdk-ecr-outputs.json)
          COGNITO_CLIENT_ID=$(jq -r '.RustAgentAgentcoreECRStack.CognitoClientId' cdk-ecr-outputs.json)

          echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT
          echo "repo_uri=$REPO_URI" >> $GITHUB_OUTPUT
          echo "cognito_discovery_url=$COGNITO_DISCOVERY_URL" >> $GITHUB_OUTPUT
          echo "cognito_client_id=$COGNITO_CLIENT_ID" >> $GITHUB_OUTPUT

      - name: Docker login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
            | docker login \
              --username AWS \
              --password-stdin ${{ steps.cdk_ecr_outputs.outputs.repo_uri }}

      - name: Build ARM64 Docker image
        run: |
          docker build \
            -t ${{ steps.cdk_ecr_outputs.outputs.repo_name }}:latest \
            .

      - name: Tag image
        run: |
          docker tag ${{ steps.cdk_ecr_outputs.outputs.repo_name }}:latest \
            ${{ steps.cdk_ecr_outputs.outputs.repo_uri }}/${{ steps.cdk_ecr_outputs.outputs.repo_name }}:latest

      - name: Push to ECR
        run: |
          docker push \
          ${{ steps.cdk_ecr_outputs.outputs.repo_uri }}/${{ steps.cdk_ecr_outputs.outputs.repo_name }}:latest

      - name: Deploy AgentCore Runtime
        working-directory: aws/ac-runtime
        run: |
          npm i
          cdk deploy -O cdk-runtime-outputs.json --require-approval never \
          --context REPO_URI=${{ steps.cdk_ecr_outputs.outputs.repo_uri }} \
          --context REPO_NAME=${{ steps.cdk_ecr_outputs.outputs.repo_name }} \
          --context COGNITO_DISCOVERY_URL=${{ steps.cdk_ecr_outputs.outputs.cognito_discovery_url }} \
          --context COGNITO_CLIENT_ID=${{ steps.cdk_ecr_outputs.outputs.cognito_client_id }}

      - name: Parse Runtime CDK outputs
        id: cdk_runtime_outputs
        working-directory: aws/ac-runtime
        run: |
          AGENT_RUNTIME_ROLE=$(jq -r '.AcRuntimeStack.AgentRuntimeRoleArn' cdk-runtime-outputs.json)
          AGENT_RUNTIME_ID=$(jq -r '.AcRuntimeStack.RustAgentId' cdk-runtime-outputs.json)

          echo "agent_runtime_role=$AGENT_RUNTIME_ROLE" >> $GITHUB_OUTPUT
          echo "agent_runtime_id=$AGENT_RUNTIME_ID" >> $GITHUB_OUTPUT

      - name: Update Agent version
        run: |
          aws bedrock-agentcore-control update-agent-runtime \
          --agent-runtime-id ${{ steps.cdk_runtime_outputs.outputs.agent_runtime_id }} \
          --agent-runtime-artifact "{
                  \"containerConfiguration\": {
                    \"containerUri\": \"${{ steps.cdk_ecr_outputs.outputs.repo_uri }}/${{ steps.cdk_ecr_outputs.outputs.repo_name }}:latest\"
                  }
                }" \
          --role-arn ${{ steps.cdk_runtime_outputs.outputs.agent_runtime_role }} \
          --network-configuration '{ "networkMode": "PUBLIC" }' \
          --region ${{ env.AWS_REGION }}
